// <auto-generated />
using DistributedLocalSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributedLocalSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DistributedLocalStorageContext))]
    partial class DistributedLocalStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DistributedLocalSystem.Infrastructure.Persistence.Entities.NetDiscoverySettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeaconIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveryTimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceSlug")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteHostIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UdpPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("net_discovery_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
