<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Backend.Infrastructure\Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\Backend.Application\Backend.Application.csproj" />
    <ProjectReference Include="..\Backend.Domain\Backend.Domain.csproj" />
    <ProjectReference Include="..\..\DistributedLocalSystem\DistributedLocalSystem.Core\DistributedLocalSystem.Core.csproj" />
    <ProjectReference Include="..\..\DistributedLocalSystem\DistributedLocalSystem.Root\DistributedLocalSystem.Root.csproj" />
  </ItemGroup>
  <!-- DistributedLocalSystem: Core + Root (композиция) -->
</Project>
