<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DistributedLocalSystem.Application\DistributedLocalSystem.Application.csproj" />
    <ProjectReference Include="..\DistributedLocalSystem.Core\DistributedLocalSystem.Core.csproj" />
    <ProjectReference Include="..\DistributedLocalSystem.Infrastructure\DistributedLocalSystem.Infrastructure.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
